name: "Terraform"

on:
  pull_request_target:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
      AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
      AWS_SUBNET_ID: ${{ secrets.AWS_SUBNET_ID }}
      AWS_INSTANCE_TYPE: ${{ secrets.AWS_INSTANCE_TYPE }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
    steps:
      - name: Checkout Forked Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/terraform
          chmod 600 ~/.ssh/terraform
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
      
      - name: Terraform Init
        run: make init

      - name: Terraform Validate
        run: make validate

      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        run: make apply

      - name: Terraform Verify
        run: |
          make verify || true

      - name: Notify Slack on Failure
        if: failure()
        run: |
          ./slack_notify.sh "${{ secrets.SLACK_WEBHOOK_URL }}" \
            "deploy-failed" \
            "Terraform Deployment" \
            "${{ github.event.pull_request.user.login }}" \
            "${{ github.event.pull_request.user.name || 'Unknown Name' }}"
